# Generated by Django 5.1.4 on 2025-01-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='primary_price',
            new_name='starting_price',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creater',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_listings', to='auctions.category'),
        ),
    ]
